# SPDX-FileCopyrightText: © 2025 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Release SARIFs Reusable"

on:
  workflow_call:

permissions: {} # yamllint disable-line rule:braces

jobs:
  ###############################################################################
  #
  #                             SECURITY JOBS
  #
  ###############################################################################
  sarif-osv-scanner:
    permissions:
      actions: "read" # https://github.com/github/codeql-action/issues/2117
      security-events: "write" # Needed to to upload SARIF file to tab
      contents: "read"
    name: "Sarif OSV-Scanner"
    # yamllint disable rule:line-length
    uses: "open-nudge/opentemplate/.github/workflows/security-osv-scanner-reusable.yml@main" # zizmor: ignore[unpinned-uses]
    # yamllint enable rule:line-length
    with:
      name: "osv-scanner-${{ github.sha }}"
      file: "osv-scanner-${{ github.sha }}.sarif"

  sarif-semgrep:
    permissions:
      actions: "read" # https://github.com/github/codeql-action/issues/2117
      security-events: "write" # Needed to upload SARIF to security tab
      contents: "read"
    name: "Sarif Semgrep"
    # yamllint disable rule:line-length
    uses: "open-nudge/opentemplate/.github/workflows/security-semgrep-reusable.yml@main" # zizmor: ignore[unpinned-uses]
    # yamllint enable rule:line-length
    with:
      name: "semgrep-${{ github.sha }}"
      file: "semgrep-${{ github.sha }}.sarif"
...
