# SPDX-FileCopyrightText: © 2025 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Security Semgrep Renovate"

on:
  pull_request:
    branches:
      - "main"
  merge_group:
    types:
      - "checks_requested"

permissions: {} # yamllint disable-line rule:braces

concurrency:
  group: >
    ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security-semgrep-renovate:
    permissions:
      actions: "read" # https://github.com/github/codeql-action/issues/2117
      security-events: "write" # Needed to to upload SARIF file to tab
      contents: "read"
    if: |
      github.event.pull_request.user.login == 'renovate[bot]'
      && github.ref == 'refs/heads/bot/dependencies-dev-security'
    name: "Security Semgrep Renovate"
    # yamllint disable rule:line-length
    uses: "open-nudge/opentemplate/.github/workflows/security-semgrep-reusable.yml@main" # zizmor: ignore[unpinned-uses]
    # yamllint enable rule:line-length
...
