# SPDX-FileCopyrightText: © 2025 open-nudge <https://github.com/open-nudge>
# SPDX-FileContributor: szymonmaszke <github@maszke.co>
#
# SPDX-License-Identifier: Apache-2.0

---
name: "Security Scorecard Update"

on:
  schedule:
    - cron: "0 3 * * 6"
  workflow_dispatch:

permissions: {} # yamllint disable-line rule:braces

jobs:
  security-scorecard-update:
    permissions:
      actions: "read" # https://github.com/github/codeql-action/issues/2117
      security-events: "write" # Needed to to upload SARIF file to tab
      id-token: "write" # Needed for GitHub OIDC token if publish_results
      contents: "read"
    name: "Security Scorecard Update"
    # yamllint disable rule:line-length
    uses: "open-nudge/opentemplate/.github/workflows/security-scorecard-reusable.yml@main" # zizmor: ignore[unpinned-uses]
    # yamllint enable rule:line-length
    with:
      sarif: true
...
